from tkinter import *
from tkinter import font
from tkinter import ttk
import tkinter as tk
class buttons:
    def __init__(self, tab2_seperate_scroll_BTN, root, tab2_load_more_btn, tab2_seperate_scroll_LOAD, keyevents_buttons, keyevents_labels, data, current_lang, background_color):
        self.tab2_seperate_scroll_BTN = tab2_seperate_scroll_BTN
        self.root = root
        self.tab2_load_more_btn = tab2_load_more_btn
        self.tab2_seperate_scroll_LOAD = tab2_seperate_scroll_LOAD
        self.data = data
        self.current_lang = current_lang
        self.background_color = background_color 

        self.keyevents_buttons = []
        self.keyevents_labels = []
        self.keyevents_labels_2 = []
        self.keyevents_labels_3 = []
        self.keyevents_labels_4 = []
        self.load_first()


    def change_bg(self,event):
        event.widget.configure(background="lightgray")
    def change_bg_leave(self, event):
        event.widget.configure(background=self.background_color)
    def load_first(self):
        for i in range(60):
            row_frame = Frame(self.tab2_seperate_scroll_BTN)
            row_frame.pack(fill=X, pady=2)
            test_label = Label(row_frame, text="Test")
            test_label.bind("<Enter>", self.change_bg)
            test_label.bind("<Leave>", self.change_bg_leave)
            test_label.pack(side="right", expand=True, fill=X)
            name = f"Input keyevent {i+1}"
            button = Button(row_frame, text=name, bg="lightblue")
            button.pack(expand=False)
            self.keyevents_buttons.append(button)
            self.keyevents_labels.append(test_label)
        print(self.keyevents_labels)
        self.keyevents_labels[0].configure(text=self.data[self.current_lang]["l21"])
        self.keyevents_labels[1].configure(text=self.data[self.current_lang]["l22"])
        self.keyevents_labels[2].configure(text=self.data[self.current_lang]["l23"])
        self.keyevents_labels[3].configure(text=self.data[self.current_lang]["l24"])
        self.keyevents_labels[4].configure(text=self.data[self.current_lang]["l25"])
        self.keyevents_labels[5].configure(text=self.data[self.current_lang]["l26"])
        self.keyevents_labels[6].configure(text=self.data[self.current_lang]["l27"])
        self.keyevents_labels[7].configure(text=self.data[self.current_lang]["l28"])
        self.keyevents_labels[8].configure(text=self.data[self.current_lang]["l29"])
        self.keyevents_labels[9].configure(text=self.data[self.current_lang]["l30"])
        self.keyevents_labels[10].configure(text=self.data[self.current_lang]["l31"])
        self.keyevents_labels[11].configure(text=self.data[self.current_lang]["l32"])
        self.keyevents_labels[12].configure(text=self.data[self.current_lang]["l33"])
        self.keyevents_labels[13].configure(text=self.data[self.current_lang]["l34"])
        self.keyevents_labels[14].configure(text=self.data[self.current_lang]["l35"])
        self.keyevents_labels[15].configure(text=self.data[self.current_lang]["l36"])
        self.keyevents_labels[16].configure(text=self.data[self.current_lang]["l37"])
        self.keyevents_labels[17].configure(text=self.data[self.current_lang]["l38"])
        self.keyevents_labels[18].configure(text=self.data[self.current_lang]["l39"])
        self.keyevents_labels[19].configure(text=self.data[self.current_lang]["l40"])
        self.keyevents_labels[20].configure(text=self.data[self.current_lang]["l41"])
        self.keyevents_labels[21].configure(text=self.data[self.current_lang]["l42"])
        self.keyevents_labels[22].configure(text=self.data[self.current_lang]["l43"])
        self.keyevents_labels[23].configure(text=self.data[self.current_lang]["l44"])
        self.keyevents_labels[24].configure(text=self.data[self.current_lang]["l45"])
        self.keyevents_labels[25].configure(text=self.data[self.current_lang]["l46"])
        self.keyevents_labels[26].configure(text=self.data[self.current_lang]["l47"])
        self.keyevents_labels[27].configure(text=self.data[self.current_lang]["l48"])
        self.keyevents_labels[28].configure(text=self.data[self.current_lang]["l49"])
        self.keyevents_labels[29].configure(text=self.data[self.current_lang]["l50"])
        self.keyevents_labels[30].configure(text=self.data[self.current_lang]["l51"])
        self.keyevents_labels[31].configure(text=self.data[self.current_lang]["l52"])
        self.keyevents_labels[32].configure(text=self.data[self.current_lang]["l53"])
        self.keyevents_labels[33].configure(text=self.data[self.current_lang]["l54"])
        self.keyevents_labels[34].configure(text=self.data[self.current_lang]["l55"])
        self.keyevents_labels[35].configure(text=self.data[self.current_lang]["l56"])
        self.keyevents_labels[36].configure(text=self.data[self.current_lang]["l57"])
        self.keyevents_labels[37].configure(text=self.data[self.current_lang]["l58"])
        self.keyevents_labels[38].configure(text=self.data[self.current_lang]["l59"])
        self.keyevents_labels[39].configure(text=self.data[self.current_lang]["l60"])
        self.keyevents_labels[40].configure(text=self.data[self.current_lang]["l61"])
        self.keyevents_labels[41].configure(text=self.data[self.current_lang]["l62"])
        self.keyevents_labels[42].configure(text=self.data[self.current_lang]["l63"])
        self.keyevents_labels[43].configure(text=self.data[self.current_lang]["l64"])
        self.keyevents_labels[44].configure(text=self.data[self.current_lang]["l65"])
        self.keyevents_labels[45].configure(text=self.data[self.current_lang]["l66"])
        self.keyevents_labels[46].configure(text=self.data[self.current_lang]["l67"])
        self.keyevents_labels[47].configure(text=self.data[self.current_lang]["l68"])
        self.keyevents_labels[48].configure(text=self.data[self.current_lang]["l69"])
        self.keyevents_labels[49].configure(text=self.data[self.current_lang]["l70"])
        self.keyevents_labels[50].configure(text=self.data[self.current_lang]["l71"])
        self.keyevents_labels[51].configure(text=self.data[self.current_lang]["l72"])
        self.keyevents_labels[52].configure(text=self.data[self.current_lang]["l73"])
        self.keyevents_labels[53].configure(text=self.data[self.current_lang]["l74"])
        self.keyevents_labels[54].configure(text=self.data[self.current_lang]["l75"])
        self.keyevents_labels[55].configure(text=self.data[self.current_lang]["l76"])
        self.keyevents_labels[56].configure(text=self.data[self.current_lang]["l77"])
        self.keyevents_labels[57].configure(text=self.data[self.current_lang]["l78"])
        self.keyevents_labels[58].configure(text=self.data[self.current_lang]["l79"])
        self.keyevents_labels[59].configure(text=self.data[self.current_lang]["l80"])
    load_clicked = 0
    def called_test_function(self):
        buttons.load_clicked += 1
        print(f"clicked test: {self.load_clicked}")
        if self.load_clicked == 1:
            self.load1()
        elif self.load_clicked == 2:
            self.load2()
        elif self.load_clicked == 3:
            self.load3()
        elif self.load_clicked == 4:
            self.load4()
        else:
            print("All keyevents loaded")

    #IF LANGUAGES CHANGED, LOAD AGAIN
    def load_again(self):
        for widgets in self.tab2_seperate_scroll_BTN.winfo_children()[:60]:
            widgets.pack_forget()
            print("Widgets deleting")
        self.keyevents_buttons.clear()
        self.keyevents_labels.clear()
        self.root.after(10, lambda: self.load_first())
        
    #SEPERATE
    def load1(self):
        print("Tıklandı-----------------------------------------")
        self.root.update_idletasks()
        self.tab2_load_more_btn.pack_forget()
        self.tab2_seperate_scroll_LOAD.pack_forget()
        for i in range(60, 120):
            row_frame = Frame(self.tab2_seperate_scroll_BTN)
            row_frame.pack(fill=X, pady=2)
            test_label = Label(row_frame, text="Test", width=65)
            test_label.pack(side="right", expand=True, fill=X)
            name = f"Input keyevent {i+1}"
            button = Button(row_frame, text=name, bg="lightblue")
            button.pack(expand=False)
            self.keyevents_buttons.append(button)
            self.keyevents_labels.append(test_label)
        self.keyevents_labels[60].configure(text=self.data[self.current_lang]["l81"])
        self.keyevents_labels[61].configure(text=self.data[self.current_lang]["l82"])
        self.keyevents_labels[62].configure(text=self.data[self.current_lang]["l83"])
        self.keyevents_labels[63].configure(text=self.data[self.current_lang]["l84"])
        self.keyevents_labels[64].configure(text=self.data[self.current_lang]["l85"])
        self.keyevents_labels[65].configure(text=self.data[self.current_lang]["l86"])
        self.keyevents_labels[66].configure(text=self.data[self.current_lang]["l87"])
        self.keyevents_labels[67].configure(text=self.data[self.current_lang]["l88"])
        self.keyevents_labels[68].configure(text=self.data[self.current_lang]["l89"])
        self.keyevents_labels[69].configure(text=self.data[self.current_lang]["l90"])
        self.keyevents_labels[70].configure(text=self.data[self.current_lang]["l91"])
        self.keyevents_labels[71].configure(text=self.data[self.current_lang]["l92"])
        self.keyevents_labels[72].configure(text=self.data[self.current_lang]["l93"])
        self.keyevents_labels[73].configure(text=self.data[self.current_lang]["l94"])
        self.keyevents_labels[74].configure(text=self.data[self.current_lang]["l95"])
        self.keyevents_labels[75].configure(text=self.data[self.current_lang]["l96"])
        self.keyevents_labels[76].configure(text=self.data[self.current_lang]["l97"])
        self.keyevents_labels[77].configure(text=self.data[self.current_lang]["l98"])
        self.keyevents_labels[78].configure(text=self.data[self.current_lang]["l99"])
        self.keyevents_labels[79].configure(text=self.data[self.current_lang]["l100"])
        self.keyevents_labels[80].configure(text=self.data[self.current_lang]["l101"])
        self.keyevents_labels[81].configure(text=self.data[self.current_lang]["l102"])
        self.keyevents_labels[82].configure(text=self.data[self.current_lang]["l103"])
        self.keyevents_labels[83].configure(text=self.data[self.current_lang]["l104"])
        self.keyevents_labels[84].configure(text=self.data[self.current_lang]["l105"])
        self.keyevents_labels[85].configure(text=self.data[self.current_lang]["l106"])
        self.keyevents_labels[86].configure(text=self.data[self.current_lang]["l107"])
        self.keyevents_labels[87].configure(text=self.data[self.current_lang]["l108"])
        self.keyevents_labels[88].configure(text=self.data[self.current_lang]["l109"])
        self.keyevents_labels[89].configure(text=self.data[self.current_lang]["l110"])
        self.keyevents_labels[90].configure(text=self.data[self.current_lang]["l111"])
        self.keyevents_labels[91].configure(text=self.data[self.current_lang]["l112"])
        self.keyevents_labels[92].configure(text=self.data[self.current_lang]["l113"])
        self.keyevents_labels[93].configure(text=self.data[self.current_lang]["l114"])
        self.keyevents_labels[94].configure(text=self.data[self.current_lang]["l115"])
        self.keyevents_labels[95].configure(text=self.data[self.current_lang]["l116"])
        self.keyevents_labels[96].configure(text=self.data[self.current_lang]["l117"])
        self.keyevents_labels[97].configure(text=self.data[self.current_lang]["l118"])
        self.keyevents_labels[98].configure(text=self.data[self.current_lang]["l119"])
        self.keyevents_labels[99].configure(text=self.data[self.current_lang]["l120"])
        self.keyevents_labels[100].configure(text=self.data[self.current_lang]["l121"])
        self.keyevents_labels[101].configure(text=self.data[self.current_lang]["l122"])
        self.keyevents_labels[102].configure(text=self.data[self.current_lang]["l123"])
        self.keyevents_labels[103].configure(text=self.data[self.current_lang]["l124"])
        self.keyevents_labels[104].configure(text=self.data[self.current_lang]["l125"])
        self.keyevents_labels[105].configure(text=self.data[self.current_lang]["l126"])
        self.keyevents_labels[106].configure(text=self.data[self.current_lang]["l127"])
        self.keyevents_labels[107].configure(text=self.data[self.current_lang]["l128"])
        self.keyevents_labels[108].configure(text=self.data[self.current_lang]["l129"])
        self.keyevents_labels[109].configure(text=self.data[self.current_lang]["l130"])
        self.keyevents_labels[110].configure(text=self.data[self.current_lang]["l131"])
        self.keyevents_labels[111].configure(text=self.data[self.current_lang]["l132"])
        self.keyevents_labels[112].configure(text=self.data[self.current_lang]["l133"])
        self.keyevents_labels[113].configure(text=self.data[self.current_lang]["l134"])
        self.keyevents_labels[114].configure(text=self.data[self.current_lang]["l135"])
        self.keyevents_labels[115].configure(text=self.data[self.current_lang]["l136"])
        self.keyevents_labels[116].configure(text=self.data[self.current_lang]["l137"])
        self.keyevents_labels[117].configure(text=self.data[self.current_lang]["l138"])
        self.keyevents_labels[118].configure(text=self.data[self.current_lang]["l139"])
        self.keyevents_labels[119].configure(text=self.data[self.current_lang]["l140"])
        self.root.after(100, lambda: self.tab2_seperate_scroll_LOAD.pack())
        self.root.after(101, lambda: self.tab2_load_more_btn.pack())
    #SEPERATE
    def load2(self):
        print("Tıklandı22222-----------------------------------------")
        self.root.update_idletasks()
        self.tab2_load_more_btn.pack_forget()
        self.tab2_seperate_scroll_LOAD.pack_forget()
        for i in range(120, 180):
            row_frame = Frame(self.tab2_seperate_scroll_BTN)
            row_frame.pack(fill=X, pady=2)
            test_label = Label(row_frame, text="Test", width=65)
            test_label.pack(side="right", expand=True, fill=X)
            name = f"Input keyevent {i+1}"
            button = Button(row_frame, text=name, bg="lightblue")
            button.pack(expand=False)
            self.keyevents_buttons.append(button)
            self.keyevents_labels.append(test_label)
        self.keyevents_labels[120].configure(text=self.data[self.current_lang]["l141"])
        self.keyevents_labels[121].configure(text=self.data[self.current_lang]["l142"])
        self.keyevents_labels[122].configure(text=self.data[self.current_lang]["l143"])
        self.keyevents_labels[123].configure(text=self.data[self.current_lang]["l144"])
        self.keyevents_labels[124].configure(text=self.data[self.current_lang]["l145"])
        self.keyevents_labels[125].configure(text=self.data[self.current_lang]["l146"])
        self.keyevents_labels[126].configure(text=self.data[self.current_lang]["l147"])
        self.keyevents_labels[127].configure(text=self.data[self.current_lang]["l148"])
        self.keyevents_labels[128].configure(text=self.data[self.current_lang]["l149"])
        self.keyevents_labels[129].configure(text=self.data[self.current_lang]["l150"])
        self.keyevents_labels[130].configure(text=self.data[self.current_lang]["l151"])
        self.keyevents_labels[131].configure(text=self.data[self.current_lang]["l152"])
        self.keyevents_labels[132].configure(text=self.data[self.current_lang]["l153"])
        self.keyevents_labels[133].configure(text=self.data[self.current_lang]["l154"])
        self.keyevents_labels[134].configure(text=self.data[self.current_lang]["l155"])
        self.keyevents_labels[135].configure(text=self.data[self.current_lang]["l156"])
        self.keyevents_labels[136].configure(text=self.data[self.current_lang]["l157"])
        self.keyevents_labels[137].configure(text=self.data[self.current_lang]["l158"])
        self.keyevents_labels[138].configure(text=self.data[self.current_lang]["l159"])
        self.keyevents_labels[139].configure(text=self.data[self.current_lang]["l160"])
        self.keyevents_labels[140].configure(text=self.data[self.current_lang]["l161"])
        self.keyevents_labels[141].configure(text=self.data[self.current_lang]["l162"])
        self.keyevents_labels[142].configure(text=self.data[self.current_lang]["l163"])
        self.keyevents_labels[143].configure(text=self.data[self.current_lang]["l164"])
        self.keyevents_labels[144].configure(text=self.data[self.current_lang]["l165"])
        self.keyevents_labels[145].configure(text=self.data[self.current_lang]["l166"])
        self.keyevents_labels[146].configure(text=self.data[self.current_lang]["l167"])
        self.keyevents_labels[147].configure(text=self.data[self.current_lang]["l168"])
        self.keyevents_labels[148].configure(text=self.data[self.current_lang]["l169"])
        self.keyevents_labels[149].configure(text=self.data[self.current_lang]["l170"])
        self.keyevents_labels[150].configure(text=self.data[self.current_lang]["l171"])
        self.keyevents_labels[151].configure(text=self.data[self.current_lang]["l172"])
        self.keyevents_labels[152].configure(text=self.data[self.current_lang]["l173"])
        self.keyevents_labels[153].configure(text=self.data[self.current_lang]["l174"])
        self.keyevents_labels[154].configure(text=self.data[self.current_lang]["l175"])
        self.keyevents_labels[155].configure(text=self.data[self.current_lang]["l176"])
        self.keyevents_labels[156].configure(text=self.data[self.current_lang]["l177"])
        self.keyevents_labels[157].configure(text=self.data[self.current_lang]["l178"])
        self.keyevents_labels[158].configure(text=self.data[self.current_lang]["l179"])
        self.keyevents_labels[159].configure(text=self.data[self.current_lang]["l180"])
        self.keyevents_labels[160].configure(text=self.data[self.current_lang]["l181"])
        self.keyevents_labels[161].configure(text=self.data[self.current_lang]["l182"])
        self.keyevents_labels[162].configure(text=self.data[self.current_lang]["l183"])
        self.keyevents_labels[163].configure(text=self.data[self.current_lang]["l184"])
        self.keyevents_labels[164].configure(text=self.data[self.current_lang]["l185"])
        self.keyevents_labels[165].configure(text=self.data[self.current_lang]["l186"])
        self.keyevents_labels[166].configure(text=self.data[self.current_lang]["l187"])
        self.keyevents_labels[167].configure(text=self.data[self.current_lang]["l188"])
        self.keyevents_labels[168].configure(text=self.data[self.current_lang]["l189"])
        self.keyevents_labels[169].configure(text=self.data[self.current_lang]["l190"])
        self.keyevents_labels[170].configure(text=self.data[self.current_lang]["l191"])
        self.keyevents_labels[171].configure(text=self.data[self.current_lang]["l192"])
        self.keyevents_labels[172].configure(text=self.data[self.current_lang]["l193"])
        self.keyevents_labels[173].configure(text=self.data[self.current_lang]["l194"])
        self.keyevents_labels[174].configure(text=self.data[self.current_lang]["l195"])
        self.keyevents_labels[175].configure(text=self.data[self.current_lang]["l196"])
        self.keyevents_labels[176].configure(text=self.data[self.current_lang]["l197"])
        self.keyevents_labels[177].configure(text=self.data[self.current_lang]["l198"])
        self.keyevents_labels[178].configure(text=self.data[self.current_lang]["l199"])
        self.keyevents_labels[179].configure(text=self.data[self.current_lang]["l200"])
        self.root.after(100, lambda: self.tab2_seperate_scroll_LOAD.pack())
        self.root.after(101, lambda: self.tab2_load_more_btn.pack())
    #SEPERATE
    def load3(self):
        print("Tıklandı33333-----------------------------------------")
        self.root.update_idletasks()
        self.tab2_load_more_btn.pack_forget()
        self.tab2_seperate_scroll_LOAD.pack_forget()
        for i in range(180, 240):
            row_frame = Frame(self.tab2_seperate_scroll_BTN)
            row_frame.pack(fill=X, pady=2)
            test_label = Label(row_frame, text="Test", width=65)
            test_label.pack(side="right", expand=True, fill=X)
            name = f"Input keyevent {i+1}"
            button = Button(row_frame, text=name, bg="lightblue")
            button.pack(expand=False)
            self.keyevents_buttons.append(button)
            self.keyevents_labels.append(test_label)
        self.keyevents_labels[180].configure(text=self.data[self.current_lang]["l201"])
        self.keyevents_labels[181].configure(text=self.data[self.current_lang]["l202"])
        self.keyevents_labels[182].configure(text=self.data[self.current_lang]["l203"])
        self.keyevents_labels[183].configure(text=self.data[self.current_lang]["l204"])
        self.keyevents_labels[184].configure(text=self.data[self.current_lang]["l205"])
        self.keyevents_labels[185].configure(text=self.data[self.current_lang]["l206"])
        self.keyevents_labels[186].configure(text=self.data[self.current_lang]["l207"])
        self.keyevents_labels[187].configure(text=self.data[self.current_lang]["l208"])
        self.keyevents_labels[188].configure(text=self.data[self.current_lang]["l209"])
        self.keyevents_labels[189].configure(text=self.data[self.current_lang]["l210"])
        self.keyevents_labels[190].configure(text=self.data[self.current_lang]["l211"])
        self.keyevents_labels[191].configure(text=self.data[self.current_lang]["l212"])
        self.keyevents_labels[192].configure(text=self.data[self.current_lang]["l213"])
        self.keyevents_labels[193].configure(text=self.data[self.current_lang]["l214"])
        self.keyevents_labels[194].configure(text=self.data[self.current_lang]["l215"])
        self.keyevents_labels[195].configure(text=self.data[self.current_lang]["l216"])
        self.keyevents_labels[196].configure(text=self.data[self.current_lang]["l217"])
        self.keyevents_labels[197].configure(text=self.data[self.current_lang]["l218"])
        self.keyevents_labels[198].configure(text=self.data[self.current_lang]["l219"])
        self.keyevents_labels[199].configure(text=self.data[self.current_lang]["l220"])
        self.keyevents_labels[200].configure(text=self.data[self.current_lang]["l221"])
        self.keyevents_labels[201].configure(text=self.data[self.current_lang]["l222"])
        self.keyevents_labels[202].configure(text=self.data[self.current_lang]["l223"])
        self.keyevents_labels[203].configure(text=self.data[self.current_lang]["l224"])
        self.keyevents_labels[204].configure(text=self.data[self.current_lang]["l225"])
        self.keyevents_labels[205].configure(text=self.data[self.current_lang]["l226"])
        self.keyevents_labels[206].configure(text=self.data[self.current_lang]["l227"])
        self.keyevents_labels[207].configure(text=self.data[self.current_lang]["l228"])
        self.keyevents_labels[208].configure(text=self.data[self.current_lang]["l229"])
        self.keyevents_labels[209].configure(text=self.data[self.current_lang]["l230"])
        self.keyevents_labels[210].configure(text=self.data[self.current_lang]["l231"])
        self.keyevents_labels[211].configure(text=self.data[self.current_lang]["l232"])
        self.keyevents_labels[212].configure(text=self.data[self.current_lang]["l233"])
        self.keyevents_labels[213].configure(text=self.data[self.current_lang]["l234"])
        self.keyevents_labels[214].configure(text=self.data[self.current_lang]["l235"])
        self.keyevents_labels[215].configure(text=self.data[self.current_lang]["l236"])
        self.keyevents_labels[216].configure(text=self.data[self.current_lang]["l237"])
        self.keyevents_labels[217].configure(text=self.data[self.current_lang]["l238"])
        self.keyevents_labels[218].configure(text=self.data[self.current_lang]["l239"])
        self.keyevents_labels[219].configure(text=self.data[self.current_lang]["l240"])
        self.keyevents_labels[220].configure(text=self.data[self.current_lang]["l241"])
        self.keyevents_labels[221].configure(text=self.data[self.current_lang]["l242"])
        self.keyevents_labels[222].configure(text=self.data[self.current_lang]["l243"])
        self.keyevents_labels[223].configure(text=self.data[self.current_lang]["l244"])
        self.keyevents_labels[224].configure(text=self.data[self.current_lang]["l245"])
        self.keyevents_labels[225].configure(text=self.data[self.current_lang]["l246"])
        self.keyevents_labels[226].configure(text=self.data[self.current_lang]["l247"])
        self.keyevents_labels[227].configure(text=self.data[self.current_lang]["l248"])
        self.keyevents_labels[228].configure(text=self.data[self.current_lang]["l249"])
        self.keyevents_labels[229].configure(text=self.data[self.current_lang]["l250"])
        self.keyevents_labels[230].configure(text=self.data[self.current_lang]["l251"])
        self.keyevents_labels[231].configure(text=self.data[self.current_lang]["l252"])
        self.keyevents_labels[232].configure(text=self.data[self.current_lang]["l253"])
        self.keyevents_labels[233].configure(text=self.data[self.current_lang]["l254"])
        self.keyevents_labels[234].configure(text=self.data[self.current_lang]["l255"])
        self.keyevents_labels[235].configure(text=self.data[self.current_lang]["l256"])
        self.keyevents_labels[236].configure(text=self.data[self.current_lang]["l257"])
        self.keyevents_labels[237].configure(text=self.data[self.current_lang]["l258"])
        self.keyevents_labels[238].configure(text=self.data[self.current_lang]["l259"])
        self.keyevents_labels[239].configure(text=self.data[self.current_lang]["l260"])
        self.root.after(100, lambda: self.tab2_seperate_scroll_LOAD.pack())
        self.root.after(101, lambda: self.tab2_load_more_btn.pack())
    #SEPERATE
    def load4(self):
        print("Tıklandı44444-----------------------------------------")
        self.root.update_idletasks()
        self.tab2_load_more_btn.pack_forget()
        self.tab2_seperate_scroll_LOAD.pack_forget()
        for i in range(240, 288):
            row_frame = Frame(self.tab2_seperate_scroll_BTN)
            row_frame.pack(fill=X, pady=2)
            test_label = Label(row_frame, text="Test", width=65)
            test_label.pack(side="right", expand=True, fill=X)
            name = f"Input keyevent {i+1}"
            button = Button(row_frame, text=name, bg="lightblue")
            button.pack(expand=False)
            self.keyevents_buttons.append(button)
            self.keyevents_labels.append(test_label)
        self.keyevents_labels[240].configure(text=self.data[self.current_lang]["l261"])
        self.keyevents_labels[241].configure(text=self.data[self.current_lang]["l262"])
        self.keyevents_labels[242].configure(text=self.data[self.current_lang]["l263"])
        self.keyevents_labels[243].configure(text=self.data[self.current_lang]["l264"])
        self.keyevents_labels[244].configure(text=self.data[self.current_lang]["l265"])
        self.keyevents_labels[245].configure(text=self.data[self.current_lang]["l266"])
        self.keyevents_labels[246].configure(text=self.data[self.current_lang]["l267"])
        self.keyevents_labels[247].configure(text=self.data[self.current_lang]["l268"])
        self.keyevents_labels[248].configure(text=self.data[self.current_lang]["l269"])
        self.keyevents_labels[249].configure(text=self.data[self.current_lang]["l270"])
        self.keyevents_labels[250].configure(text=self.data[self.current_lang]["l271"])
        self.keyevents_labels[251].configure(text=self.data[self.current_lang]["l272"])
        self.keyevents_labels[252].configure(text=self.data[self.current_lang]["l273"])
        self.keyevents_labels[253].configure(text=self.data[self.current_lang]["l274"])
        self.keyevents_labels[254].configure(text=self.data[self.current_lang]["l275"])
        self.keyevents_labels[255].configure(text=self.data[self.current_lang]["l276"])
        self.keyevents_labels[256].configure(text=self.data[self.current_lang]["l277"])
        self.keyevents_labels[257].configure(text=self.data[self.current_lang]["l278"])
        self.keyevents_labels[258].configure(text=self.data[self.current_lang]["l279"])
        self.keyevents_labels[259].configure(text=self.data[self.current_lang]["l280"])
        self.keyevents_labels[260].configure(text=self.data[self.current_lang]["l281"])
        self.keyevents_labels[261].configure(text=self.data[self.current_lang]["l282"])
        self.keyevents_labels[262].configure(text=self.data[self.current_lang]["l283"])
        self.keyevents_labels[263].configure(text=self.data[self.current_lang]["l284"])
        self.keyevents_labels[264].configure(text=self.data[self.current_lang]["l285"])
        self.keyevents_labels[265].configure(text=self.data[self.current_lang]["l286"])
        self.keyevents_labels[266].configure(text=self.data[self.current_lang]["l287"])
        self.keyevents_labels[267].configure(text=self.data[self.current_lang]["l288"])
        self.keyevents_labels[268].configure(text=self.data[self.current_lang]["l289"])
        self.keyevents_labels[269].configure(text=self.data[self.current_lang]["l290"])
        self.keyevents_labels[270].configure(text=self.data[self.current_lang]["l291"])
        self.keyevents_labels[271].configure(text=self.data[self.current_lang]["l292"])
        self.keyevents_labels[272].configure(text=self.data[self.current_lang]["l293"])
        self.keyevents_labels[273].configure(text=self.data[self.current_lang]["l294"])
        self.keyevents_labels[274].configure(text=self.data[self.current_lang]["l295"])
        self.keyevents_labels[275].configure(text=self.data[self.current_lang]["l296"])
        self.keyevents_labels[276].configure(text=self.data[self.current_lang]["l297"])
        self.keyevents_labels[277].configure(text=self.data[self.current_lang]["l298"])
        self.keyevents_labels[278].configure(text=self.data[self.current_lang]["l299"])
        self.keyevents_labels[279].configure(text=self.data[self.current_lang]["l300"])
        self.keyevents_labels[280].configure(text=self.data[self.current_lang]["l301"])
        self.keyevents_labels[281].configure(text=self.data[self.current_lang]["l302"])
        self.keyevents_labels[282].configure(text=self.data[self.current_lang]["l303"])
        self.keyevents_labels[283].configure(text=self.data[self.current_lang]["l304"])
        self.keyevents_labels[284].configure(text=self.data[self.current_lang]["l305"])
        self.keyevents_labels[285].configure(text=self.data[self.current_lang]["l306"])
        self.keyevents_labels[286].configure(text=self.data[self.current_lang]["l307"])
        self.keyevents_labels[287].configure(text=self.data[self.current_lang]["l308"])
        self.root.after(100, lambda: self.tab2_seperate_scroll_LOAD.pack())
        self.root.after(101, lambda: self.tab2_load_more_btn.pack())
