from tkinter import *
from tkinter import font
from tkinter import ttk
import tkinter as tk
class buttons:
    def __init__(self, tab2_seperate_scroll_BTN, root, tab2_load_more_btn, tab2_seperate_scroll_LOAD, keyevents_buttons, keyevents_labels):
        self.tab2_seperate_scroll_BTN = tab2_seperate_scroll_BTN
        self.root = root
        self.tab2_load_more_btn = tab2_load_more_btn
        self.tab2_seperate_scroll_LOAD = tab2_seperate_scroll_LOAD

        self.keyevents_buttons = []
        self.keyevents_labels = []
        self.keyevents_labels_2 = []
        self.keyevents_labels_3 = []
        self.keyevents_labels_4 = []
        for i in range(60):
            row_frame = Frame(tab2_seperate_scroll_BTN)
            row_frame.pack(fill=X, pady=2)
            test_label = Label(row_frame, text="Test", width=65)
            test_label.pack(side="right", expand=True)
            name = f"Input keyevent {i+1}"
            buton = Button(row_frame, text=name, bg="lightblue")
            buton.pack()
            keyevents_buttons.append(buton)
            self.keyevents_labels.append(test_label)
        print(self.keyevents_labels)
        self.keyevents_labels[0].configure(text="It simulates a press of the soft left key (KEYCODE_SOFT_LEFT) on your device")
        self.keyevents_labels[1].configure(text="It simulates a press of the soft right key.")
        self.keyevents_labels[2].configure(text="It simulates a press of the Home button")
        self.keyevents_labels[3].configure(text="It simulates a press of the Back button")
        self.keyevents_labels[4].configure(text="It simulates a press of the Call button")
        self.keyevents_labels[5].configure(text="It simulates a press of the End Call button")
        self.keyevents_labels[6].configure(text="It simulates a press of the '0' number key")
        self.keyevents_labels[7].configure(text="It simulates a press of the '1' number key")
        self.keyevents_labels[8].configure(text="It simulates a press of the '2' number key")
        self.keyevents_labels[9].configure(text="It simulates a press of the '3' number key")
        self.keyevents_labels[10].configure(text="It simulates a press of the '4' number key")
        self.keyevents_labels[11].configure(text="It simulates a press of the '5' number key")
        self.keyevents_labels[12].configure(text="It simulates a press of the '6' number key")
        self.keyevents_labels[13].configure(text="It simulates a press of the '7' number key")
        self.keyevents_labels[14].configure(text="It simulates a press of the '8' number key")
        self.keyevents_labels[15].configure(text="It simulates a press of the '9' number key")
        self.keyevents_labels[16].configure(text="It simulates a press of the Star (*) key")
        self.keyevents_labels[17].configure(text="It simulates a press of the Pound (#) key")
        self.keyevents_labels[18].configure(text="It simulates a press of the D-pad Up button")
        self.keyevents_labels[19].configure(text="It simulates a press of the D-pad Down button")
        self.keyevents_labels[20].configure(text="It simulates a press of the D-pad Left button")
        self.keyevents_labels[21].configure(text="It simulates a press of the D-pad Right button")
        self.keyevents_labels[22].configure(text="It simulates a press of the D-pad Center button")
        self.keyevents_labels[23].configure(text="It simulates a press of the Volume Up button")
        self.keyevents_labels[24].configure(text="It simulates a press of the Volume Down button")
        self.keyevents_labels[25].configure(text="It simulates a press of the Power button")
        self.keyevents_labels[26].configure(text="It simulates a press of the Camera button")
        self.keyevents_labels[27].configure(text="It simulates a press of the Clear key")
        self.keyevents_labels[28].configure(text="It simulates a press of the 'A' key")
        self.keyevents_labels[29].configure(text="It simulates a press of the 'B' key")
        self.keyevents_labels[30].configure(text="It simulates a press of the 'C' key")
        self.keyevents_labels[31].configure(text="It simulates a press of the 'D' key")
        self.keyevents_labels[32].configure(text="It simulates a press of the 'E' key")
        self.keyevents_labels[33].configure(text="It simulates a press of the 'F' key")
        self.keyevents_labels[34].configure(text="It simulates a press of the 'G' key")
        self.keyevents_labels[35].configure(text="It simulates a press of the 'H' key")
        self.keyevents_labels[36].configure(text="It simulates a press of the 'I' key")
        self.keyevents_labels[37].configure(text="It simulates a press of the 'J' key")
        self.keyevents_labels[38].configure(text="It simulates a press of the 'K' key")
        self.keyevents_labels[39].configure(text="It simulates a press of the 'L' key")
        self.keyevents_labels[40].configure(text="It simulates a press of the 'M' key")
        self.keyevents_labels[41].configure(text="It simulates a press of the 'N' key")
        self.keyevents_labels[42].configure(text="It simulates a press of the 'O' key")
        self.keyevents_labels[43].configure(text="It simulates a press of the 'P' key")
        self.keyevents_labels[44].configure(text="It simulates a press of the 'Q' key")
        self.keyevents_labels[45].configure(text="It simulates a press of the 'R' key")
        self.keyevents_labels[46].configure(text="It simulates a press of the 'S' key")
        self.keyevents_labels[47].configure(text="It simulates a press of the 'T' key")
        self.keyevents_labels[48].configure(text="It simulates a press of the 'U' key")
        self.keyevents_labels[49].configure(text="It simulates a press of the 'V' key")
        self.keyevents_labels[50].configure(text="It simulates a press of the 'W' key")
        self.keyevents_labels[51].configure(text="It simulates a press of the 'X' key")
        self.keyevents_labels[52].configure(text="It simulates a press of the 'Y' key")
        self.keyevents_labels[53].configure(text="It simulates a press of the 'Z' key")
        self.keyevents_labels[54].configure(text="It simulates a press of the Comma (,) key")
        self.keyevents_labels[55].configure(text="It simulates a press of the Period (.) key")
        self.keyevents_labels[56].configure(text="It simulates a press of the Left Alt key")
        self.keyevents_labels[57].configure(text="It simulates a press of the Right Alt key")
        self.keyevents_labels[58].configure(text="It simulates a press of the Left Shift key")
        self.keyevents_labels[59].configure(text="It simulates a press of the Right Shift key")
    load_clicked = 0
    def called_test_function(self):
        buttons.load_clicked += 1
        print(f"clicked test: {self.load_clicked}")
        if self.load_clicked == 1:
            self.load1()
        elif self.load_clicked == 2:
            self.load2()
        elif self.load_clicked == 3:
            self.load3()
        else:
            print("All keyevents loaded")
    #SEPERATE
    def load1(self):
        print("Tıklandı-----------------------------------------")
        self.root.update_idletasks()
        self.tab2_load_more_btn.pack_forget()
        self.tab2_seperate_scroll_LOAD.pack_forget()
        for i in range(60, 120):
            row_frame = Frame(self.tab2_seperate_scroll_BTN)
            row_frame.pack(fill=X, pady=2)
            test_label = Label(row_frame, text="Test", width=65)
            test_label.pack(side="right", expand=True)
            name = f"Input keyevent {i+1}"
            buton = Button(row_frame, text=name, bg="lightblue")
            buton.pack()
            self.keyevents_buttons.append(buton)
            self.keyevents_labels.append(test_label)
        self.keyevents_labels[60].configure(text="It simulates a press of the Tab key")
        self.keyevents_labels[61].configure(text="It simulates a press of the Space key")
        self.keyevents_labels[62].configure(text="It simulates a press of the Symbol key")
        self.keyevents_labels[63].configure(text="It simulates a press of the Explorer (Browser) key")
        self.keyevents_labels[64].configure(text="It simulates a press of the Envelope (Mail) key")
        self.keyevents_labels[65].configure(text="It simulates a press of the Enter key")
        self.keyevents_labels[66].configure(text="It simulates a press of the Delete (Backspace) key")
        self.keyevents_labels[67].configure(text="It simulates a press of the Grave (`) key")
        self.keyevents_labels[68].configure(text="It simulates a press of the Minus (-) key")
        self.keyevents_labels[69].configure(text="It simulates a press of the Equals (=) key")
        self.keyevents_labels[70].configure(text="It simulates a press of the Left Bracket ([) key")
        self.keyevents_labels[71].configure(text="It simulates a press of the Right Bracket (]) key")
        self.keyevents_labels[72].configure(text="It simulates a press of the Backslash (\) key")
        self.keyevents_labels[73].configure(text="It simulates a press of the Semicolon (;) key")
        self.keyevents_labels[74].configure(text="It simulates a press of the Apostrophe (') key")
        self.keyevents_labels[75].configure(text="It simulates a press of the Slash (/) key")
        self.keyevents_labels[76].configure(text="It simulates a press of the At (@) key")
        self.keyevents_labels[77].configure(text="It simulates a press of the Num Lock key")
        self.keyevents_labels[78].configure(text="It simulates a press of the Headset Hook key")
        self.keyevents_labels[79].configure(text="It simulates a press of the Camera Focus key")
        self.keyevents_labels[80].configure(text="It simulates a press of the Plus (+) key")
        self.keyevents_labels[81].configure(text="It simulates a press of the Menu key")
        self.keyevents_labels[82].configure(text="It simulates a press of the Notification key")
        self.keyevents_labels[83].configure(text="It simulates a press of the Search key")
        self.keyevents_labels[84].configure(text="It simulates a press of the Media Play/Pause key")
        self.keyevents_labels[85].configure(text="It simulates a press of the Media Stop key")
        self.keyevents_labels[86].configure(text="It simulates a press of the Media Next key")
        self.keyevents_labels[87].configure(text="It simulates a press of the Media Previous key")
        self.keyevents_labels[88].configure(text="It simulates a press of the Media Rewind key")
        self.keyevents_labels[89].configure(text="It simulates a press of the Media Fast Forward key")
        self.keyevents_labels[90].configure(text="It simulates a press of the Mute key")
        self.keyevents_labels[91].configure(text="It simulates a press of the Page Up key")
        self.keyevents_labels[92].configure(text="It simulates a press of the Page Down key")
        self.keyevents_labels[93].configure(text="It simulates a press of the Picture Symbols key")
        self.keyevents_labels[94].configure(text="It simulates a press of the Switch Charset key")
        self.keyevents_labels[95].configure(text="It simulates a press of the Gamepad A button")
        self.keyevents_labels[96].configure(text="It simulates a press of the Gamepad B button")
        self.keyevents_labels[97].configure(text="It simulates a press of the Gamepad C button")
        self.keyevents_labels[98].configure(text="It simulates a press of the Gamepad X button")
        self.keyevents_labels[99].configure(text="It simulates a press of the Gamepad Y button")
        self.keyevents_labels[100].configure(text="It simulates a press of the Gamepad Z button")
        self.keyevents_labels[101].configure(text="It simulates a press of the Gamepad L1 button")
        self.keyevents_labels[102].configure(text="It simulates a press of the Gamepad R1 button")
        self.keyevents_labels[103].configure(text="It simulates a press of the Gamepad L2 button")
        self.keyevents_labels[104].configure(text="It simulates a press of the Gamepad R2 button")
        self.keyevents_labels[105].configure(text="It simulates a press of the Gamepad Left Thumb button")
        self.keyevents_labels[106].configure(text="It simulates a press of the Gamepad Right Thumb button")
        self.keyevents_labels[107].configure(text="It simulates a press of the Gamepad Start button")
        self.keyevents_labels[108].configure(text="It simulates a press of the Gamepad Select button")
        self.keyevents_labels[109].configure(text="It simulates a press of the Gamepad Mode button")
        self.keyevents_labels[110].configure(text="It simulates a press of the Escape key")
        self.keyevents_labels[111].configure(text="It simulates a press of the Forward Delete key")
        self.keyevents_labels[112].configure(text="It simulates a press of the Left Control key")
        self.keyevents_labels[113].configure(text="It simulates a press of the Right Control key")
        self.keyevents_labels[114].configure(text="It simulates a press of the Caps Lock key")
        self.keyevents_labels[115].configure(text="It simulates a press of the Scroll Lock key")
        self.keyevents_labels[116].configure(text="It simulates a press of the Left Meta (Windows/Command) key")
        self.keyevents_labels[117].configure(text="It simulates a press of the Right Meta (Windows/Command) key")
        self.keyevents_labels[118].configure(text="It simulates a press of the Function (Fn) key")
        self.keyevents_labels[119].configure(text="It simulates a press of the System Request / Print Screen key")
        self.root.after(100, lambda: self.tab2_seperate_scroll_LOAD.pack())
        self.root.after(101, lambda: self.tab2_load_more_btn.pack())
    #SEPERATE
    def load2(self):
        print("Tıklandı22222-----------------------------------------")
        self.root.update_idletasks()
        self.tab2_load_more_btn.pack_forget()
        self.tab2_seperate_scroll_LOAD.pack_forget()
        for i in range(120, 180):
            row_frame = Frame(self.tab2_seperate_scroll_BTN)
            row_frame.pack(fill=X, pady=2)
            test_label = Label(row_frame, text="Test", width=65)
            test_label.pack(side="right", expand=True)
            name = f"Input keyevent {i+1}"
            buton = Button(row_frame, text=name, bg="lightblue")
            buton.pack()
            self.keyevents_buttons.append(buton)
            self.keyevents_labels.append(test_label)
        self.keyevents_labels[120].configure(text="It simulates a press of the Break / Pause key")
        self.keyevents_labels[121].configure(text="It simulates a press of the Home (Move to start) key")
        self.keyevents_labels[122].configure(text="It simulates a press of the End (Move to end) key")
        self.keyevents_labels[123].configure(text="It simulates a press of the Insert key")
        self.keyevents_labels[124].configure(text="It simulates a press of the Forward key")
        self.keyevents_labels[125].configure(text="It simulates a press of the Media Play key")
        self.keyevents_labels[126].configure(text="It simulates a press of the Media Pause key")
        self.keyevents_labels[127].configure(text="It simulates a press of the Media Close key")
        self.keyevents_labels[128].configure(text="It simulates a press of the Media Eject key")
        self.keyevents_labels[129].configure(text="It simulates a press of the Media Record key")
        self.keyevents_labels[130].configure(text="It simulates a press of the F1 key")
        self.keyevents_labels[131].configure(text="It simulates a press of the F2 key")
        self.keyevents_labels[132].configure(text="It simulates a press of the F3 key")
        self.keyevents_labels[133].configure(text="It simulates a press of the F4 key")
        self.keyevents_labels[134].configure(text="It simulates a press of the F5 key")
        self.keyevents_labels[135].configure(text="It simulates a press of the F6 key")
        self.keyevents_labels[136].configure(text="It simulates a press of the F7 key")
        self.keyevents_labels[137].configure(text="It simulates a press of the F8 key")
        self.keyevents_labels[138].configure(text="It simulates a press of the F9 key")
        self.keyevents_labels[139].configure(text="It simulates a press of the F10 key")
        self.keyevents_labels[140].configure(text="It simulates a press of the F11 key")
        self.keyevents_labels[141].configure(text="It simulates a press of the F12 key")
        self.keyevents_labels[142].configure(text="It simulates a press of the Num Lock key")
        self.keyevents_labels[143].configure(text="It simulates a press of the Numpad 0 key")
        self.keyevents_labels[144].configure(text="It simulates a press of the Numpad 1 key")
        self.keyevents_labels[145].configure(text="It simulates a press of the Numpad 2 key")
        self.keyevents_labels[146].configure(text="It simulates a press of the Numpad 3 key")
        self.keyevents_labels[147].configure(text="It simulates a press of the Numpad 4 key")
        self.keyevents_labels[148].configure(text="It simulates a press of the Numpad 5 key")
        self.keyevents_labels[149].configure(text="It simulates a press of the Numpad 6 key")
        self.keyevents_labels[150].configure(text="It simulates a press of the Numpad 7 key")
        self.keyevents_labels[151].configure(text="It simulates a press of the Numpad 8 key")
        self.keyevents_labels[152].configure(text="It simulates a press of the Numpad 9 key")
        self.keyevents_labels[153].configure(text="It simulates a press of the Numpad Divide (/) key")
        self.keyevents_labels[154].configure(text="It simulates a press of the Numpad Multiply (*) key")
        self.keyevents_labels[155].configure(text="It simulates a press of the Numpad Subtract (-) key")
        self.keyevents_labels[156].configure(text="It simulates a press of the Numpad Add (+) key")
        self.keyevents_labels[157].configure(text="It simulates a press of the Numpad Dot (.) key")
        self.keyevents_labels[158].configure(text="It simulates a press of the Numpad Comma (,) key")
        self.keyevents_labels[159].configure(text="It simulates a press of the Numpad Enter key")
        self.keyevents_labels[160].configure(text="It simulates a press of the Numpad Equals (=) key")
        self.keyevents_labels[161].configure(text="It simulates a press of the Numpad Left Parenthesis key")
        self.keyevents_labels[162].configure(text="It simulates a press of the Numpad Right Parenthesis key")
        self.keyevents_labels[163].configure(text="It simulates a press of the Volume Mute key")
        self.keyevents_labels[164].configure(text="It simulates a press of the Info key")
        self.keyevents_labels[165].configure(text="It simulates a press of the Channel Up key")
        self.keyevents_labels[166].configure(text="It simulates a press of the Channel Down key")
        self.keyevents_labels[167].configure(text="It simulates a press of the Zoom In key")
        self.keyevents_labels[168].configure(text="It simulates a press of the Zoom Out key")
        self.keyevents_labels[169].configure(text="It simulates a press of the TV key")
        self.keyevents_labels[170].configure(text="It simulates a press of the Window key")
        self.keyevents_labels[171].configure(text="It simulates a press of the Guide key")
        self.keyevents_labels[172].configure(text="It simulates a press of the DVR key")
        self.keyevents_labels[173].configure(text="It simulates a press of the Bookmark key")
        self.keyevents_labels[174].configure(text="It simulates a press of the Captions key")
        self.keyevents_labels[175].configure(text="It simulates a press of the Settings key")
        self.keyevents_labels[176].configure(text="It simulates a press of the TV Power key")
        self.keyevents_labels[177].configure(text="It simulates a press of the TV Input key")
        self.keyevents_labels[178].configure(text="It simulates a press of the Set-top Box Power key")
        self.keyevents_labels[179].configure(text="It simulates a press of the Set-top Box Input key")
        self.root.after(100, lambda: self.tab2_seperate_scroll_LOAD.pack())
        self.root.after(101, lambda: self.tab2_load_more_btn.pack())
    #SEPERATE
    def load3(self):
        print("Tıklandı33333-----------------------------------------")
        self.root.update_idletasks()
        self.tab2_load_more_btn.pack_forget()
        self.tab2_seperate_scroll_LOAD.pack_forget()
        for i in range(180, 240):
            row_frame = Frame(self.tab2_seperate_scroll_BTN)
            row_frame.pack(fill=X, pady=2)
            test_label = Label(row_frame, text="Test", width=65)
            test_label.pack(side="right", expand=True)
            name = f"Input keyevent {i+1}"
            buton = Button(row_frame, text=name, bg="lightblue")
            buton.pack()
            self.keyevents_buttons.append(buton)
            self.keyevents_labels.append(test_label)
        self.keyevents_labels[180].configure(text="It simulates a press of the A/V Receiver Power key")
        self.keyevents_labels[181].configure(text="It simulates a press of the A/V Receiver Input key")
        self.keyevents_labels[182].configure(text="It simulates a press of the Program Red key")
        self.keyevents_labels[183].configure(text="It simulates a press of the Program Green key")
        self.keyevents_labels[184].configure(text="It simulates a press of the Program Yellow key")
        self.keyevents_labels[185].configure(text="It simulates a press of the Program Blue key")
        self.keyevents_labels[186].configure(text="It simulates a press of the App Switch key")
        self.keyevents_labels[187].configure(text="It simulates a press of the Generic Button 1 key")
        self.keyevents_labels[188].configure(text="It simulates a press of the Generic Button 2 key")
        self.keyevents_labels[189].configure(text="It simulates a press of the Generic Button 3 key")
        self.keyevents_labels[190].configure(text="It simulates a press of the Generic Button 4 key")
        self.keyevents_labels[191].configure(text="It simulates a press of the Generic Button 5 key")
        self.keyevents_labels[192].configure(text="It simulates a press of the Generic Button 6 key")
        self.keyevents_labels[193].configure(text="It simulates a press of the Generic Button 7 key")
        self.keyevents_labels[194].configure(text="It simulates a press of the Generic Button 8 key")
        self.keyevents_labels[195].configure(text="It simulates a press of the Generic Button 9 key")
        self.keyevents_labels[196].configure(text="It simulates a press of the Generic Button 10 key")
        self.keyevents_labels[197].configure(text="It simulates a press of the Generic Button 11 key")
        self.keyevents_labels[198].configure(text="It simulates a press of the Generic Button 12 key")
        self.keyevents_labels[199].configure(text="It simulates a press of the Generic Button 13 key")
        self.keyevents_labels[200].configure(text="It simulates a press of the Generic Button 14 key")
        self.keyevents_labels[201].configure(text="It simulates a press of the Generic Button 15 key")
        self.keyevents_labels[202].configure(text="It simulates a press of the Generic Button 16 key")
        self.keyevents_labels[203].configure(text="It simulates a press of the Language Switch key")
        self.keyevents_labels[204].configure(text="It simulates a press of the Manner Mode key")
        self.keyevents_labels[205].configure(text="It simulates a press of the 3D Mode key")
        self.keyevents_labels[206].configure(text="It simulates a press of the Contacts key")
        self.keyevents_labels[207].configure(text="It simulates a press of the Calendar key")
        self.keyevents_labels[208].configure(text="It simulates a press of the Music key")
        self.keyevents_labels[209].configure(text="It simulates a press of the Calculator key")
        self.keyevents_labels[210].configure(text="It simulates a press of the Zenkaku/Hankaku (Japanese) key")
        self.keyevents_labels[211].configure(text="It simulates a press of the Eisu (Japanese) key")
        self.keyevents_labels[212].configure(text="It simulates a press of the Muhenkan (Japanese) key")
        self.keyevents_labels[213].configure(text="It simulates a press of the Henkan (Japanese) key")
        self.keyevents_labels[214].configure(text="It simulates a press of the Katakana/Hiragana (Japanese) key")
        self.keyevents_labels[215].configure(text="It simulates a press of the Yen (Japanese) key")
        self.keyevents_labels[216].configure(text="It simulates a press of the Ro (Japanese) key")
        self.keyevents_labels[217].configure(text="It simulates a press of the Kana (Japanese) key")
        self.keyevents_labels[218].configure(text="It simulates a press of the Assist key")
        self.keyevents_labels[219].configure(text="It simulates a press of the Brightness Down key")
        self.keyevents_labels[220].configure(text="It simulates a press of the Brightness Up key")
        self.keyevents_labels[221].configure(text="It simulates a press of the Media Audio Track key")
        self.keyevents_labels[222].configure(text="It simulates a press of the Sleep key")
        self.keyevents_labels[223].configure(text="It simulates a press of the Wakeup key")
        self.keyevents_labels[224].configure(text="It simulates a press of the Pairing key")
        self.keyevents_labels[225].configure(text="It simulates a press of the Media Top Menu key")
        self.keyevents_labels[226].configure(text="It simulates a press of the '11' number key")
        self.keyevents_labels[227].configure(text="It simulates a press of the '12' number key")
        self.keyevents_labels[228].configure(text="It simulates a press of the Last Channel key")
        self.keyevents_labels[229].configure(text="It simulates a press of the TV Data Service key")
        self.keyevents_labels[230].configure(text="It simulates a press of the Voice Assist key")
        self.keyevents_labels[231].configure(text="It simulates a press of the TV Radio Service key")
        self.keyevents_labels[232].configure(text="It simulates a press of the TV Teletext key")
        self.keyevents_labels[233].configure(text="It simulates a press of the TV Number Entry key")
        self.keyevents_labels[234].configure(text="It simulates a press of the TV Terrestrial Analog key")
        self.keyevents_labels[235].configure(text="It simulates a press of the TV Terrestrial Digital key")
        self.keyevents_labels[236].configure(text="It simulates a press of the TV Satellite key")
        self.keyevents_labels[237].configure(text="It simulates a press of the TV Satellite BS key")
        self.keyevents_labels[238].configure(text="It simulates a press of the TV Satellite CS key")
        self.keyevents_labels[239].configure(text="It simulates a press of the TV Satellite Service key")
        self.root.after(100, lambda: self.tab2_seperate_scroll_LOAD.pack())
        self.root.after(101, lambda: self.tab2_load_more_btn.pack())
    #SEPERATE
    def load4(self):
        self.keyevents_labels[240].configure(text="It simulates a press of the TV Network key")
        self.keyevents_labels[241].configure(text="It simulates a press of the TV Antenna Cable key")
        self.keyevents_labels[242].configure(text="It simulates a press of the TV Input HDMI 1 key")
        self.keyevents_labels[243].configure(text="It simulates a press of the TV Input HDMI 2 key")
        self.keyevents_labels[244].configure(text="It simulates a press of the TV Input HDMI 3 key")
        self.keyevents_labels[245].configure(text="It simulates a press of the TV Input HDMI 4 key")
        self.keyevents_labels[246].configure(text="It simulates a press of the TV Input Composite 1 key")
        self.keyevents_labels[247].configure(text="It simulates a press of the TV Input Composite 2 key")
        self.keyevents_labels[248].configure(text="It simulates a press of the TV Input Component 1 key")
        self.keyevents_labels[249].configure(text="It simulates a press of the TV Input Component 2 key")
        self.keyevents_labels[250].configure(text="It simulates a press of the TV Input VGA 1 key")
        self.keyevents_labels[251].configure(text="It simulates a press of the TV Audio Description key")
        self.keyevents_labels[252].configure(text="It simulates a press of the TV Audio Description Mix Up key")
        self.keyevents_labels[253].configure(text="It simulates a press of the TV Audio Description Mix Down key")
        self.keyevents_labels[254].configure(text="It simulates a press of the TV Zoom Mode key")
        self.keyevents_labels[255].configure(text="It simulates a press of the TV Contents Menu key")
        self.keyevents_labels[256].configure(text="It simulates a press of the TV Media Context Menu key")
        self.keyevents_labels[257].configure(text="It simulates a press of the TV Timer Programming key")
        self.keyevents_labels[258].configure(text="It simulates a press of the Help key")
        self.keyevents_labels[259].configure(text="It simulates a press of the Navigate Previous key")
        self.keyevents_labels[260].configure(text="It simulates a press of the Navigate Next key")
        self.keyevents_labels[261].configure(text="It simulates a press of the Navigate In key")
        self.keyevents_labels[262].configure(text="It simulates a press of the Navigate Out key")
        self.keyevents_labels[263].configure(text="It simulates a press of the Stem Primary key")
        self.keyevents_labels[264].configure(text="It simulates a press of the Stem 1 key")
        self.keyevents_labels[265].configure(text="It simulates a press of the Stem 2 key")
        self.keyevents_labels[266].configure(text="It simulates a press of the Stem 3 key")
        self.keyevents_labels[267].configure(text="It simulates a press of the D-pad Up-Left button")
        self.keyevents_labels[268].configure(text="It simulates a press of the D-pad Down-Left button")
        self.keyevents_labels[269].configure(text="It simulates a press of the D-pad Up-Right button")
        self.keyevents_labels[270].configure(text="It simulates a press of the D-pad Down-Right button")
        self.keyevents_labels[271].configure(text="It simulates a press of the Media Skip Forward key")
        self.keyevents_labels[272].configure(text="It simulates a press of the Media Skip Backward key")
        self.keyevents_labels[273].configure(text="It simulates a press of the Media Step Forward key")
        self.keyevents_labels[274].configure(text="It simulates a press of the Media Step Backward key")
        self.keyevents_labels[275].configure(text="It simulates a press of the Soft Sleep key")
        self.keyevents_labels[276].configure(text="It simulates a press of the Cut key")
        self.keyevents_labels[277].configure(text="It simulates a press of the Copy key")
        self.keyevents_labels[278].configure(text="It simulates a press of the Paste key")
        self.keyevents_labels[279].configure(text="It simulates a press of the System Navigation Up key")
        self.keyevents_labels[280].configure(text="It simulates a press of the System Navigation Down key")
        self.keyevents_labels[281].configure(text="It simulates a press of the System Navigation Left key")
        self.keyevents_labels[282].configure(text="It simulates a press of the System Navigation Right key")
        self.keyevents_labels[283].configure(text="It simulates a press of the All Apps key")
        self.keyevents_labels[284].configure(text="It simulates a press of the Refresh key")
        self.keyevents_labels[285].configure(text="It simulates a press of the Thumbs Up key")
        self.keyevents_labels[286].configure(text="It simulates a press of the Thumbs Down key")
        self.keyevents_labels[287].configure(text="It simulates a press of the Profile Switch key")
        self.root.after(100, lambda: self.tab2_seperate_scroll_LOAD.pack())
        self.root.after(101, lambda: self.tab2_load_more_btn.pack())